/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_leth_cropimage_CropLib */

#ifndef _Included_com_leth_cropimage_CropLib
#define _Included_com_leth_cropimage_CropLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_leth_cropimage_CropLib
 * Method:    nativeCrop
 * Signature: (Landroid/graphics/Bitmap;[I[I)V
 */
JNIEXPORT void JNICALL Java_com_leth_cropimage_CropLib_nativeCrop
  (JNIEnv *, jclass, jobject, jobject, jintArray, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
